### PR TITLE
Remove several outdated files

### PR DESCRIPTION
**Pull request by 0foxes**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/ProPAL/5)

### CODE REVIEW

**Comment by Artem-Sotnikov** [comment]
We can probably move the diagram into a folder - it's useful documentation

**Comment by 0foxes** [comment]
I think we should move it into the README.md. Also, are there any files I
missed?

**Comment by 0foxes** [comment]
How about this structure? The intent is that over time, there will be more files in docs/. Also, do you foresee us ever needing any of the fuel grain code from the other branch?

**Review by Artem-Sotnikov — APPROVED** [review]
New structure works, definitely makes the repo easier to read. 
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/ProPAL/5#-:-NeYjaUL1qlVpOOXMPqQ:b3xi1wl)* status: 0 of 18 files reviewed, all discussions resolved

**Pull request merged**
